apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-catalog-service
  template:
    metadata:
      labels:
        app: movie-catalog-service
    spec:
      containers:
        - name: movie-catalog-service
          image: otniel217/simples-k8s-springboot:movie-catalog-service-latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_NAME
              value: movie-catalog-service
            - name: SERVER_PORT
              value: "8081"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka
