apiVersion: v1
kind: ConfigMap
metadata:
  name: cinema-catalog-config
data:
  DB: cinemas
  DB_USER: cristian
  DB_PASS: cristianPassword2017
  DB_REPLS: rs1
  DB_SERVERS: "mongodb:27017"
  PORT: "3000"
